name: CI/CD to EKS

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: latest
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-bedrock:${{ env.IMAGE_TAG }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-bedrock:${{ env.IMAGE_TAG }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}

      - name: Deploy to EKS
        run: kubectl apply -f k8s/deployment.yaml

      - name: Restart Deployment (to pull new image)
        run: kubectl rollout restart deployment flask-bedrock
